{% set version = "1.3.0" %}

package:
  name: gpflow
  version: {{ version }}

source:
  fn: GPflow-{{ version }}.tar.gz
  url: https://github.com/GPflow/GPflow/archive/v{{ version }}.tar.gz
  sha256: c3603a93de848107cbc8ef1b8e768a6ea181da37eda5ffc0f69079dbd1021ed9

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  skip: true  # [python < 3.5]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.10.0
    - scipy >=0.18.0
    - pandas >=0.18.1
    - tensorflow
    - multipledispatch >=0.4.9
    - pytest >=3.5.0

test:
  imports:
    # Skip the import test on Linux, see tensorflow recipe
    - gpflow  # [not linux]

about:
  home: https://github.com/GPflow/GPflow/
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: Gaussian process methods in tensorflow

extra:
  recipe-maintainers:
    - cxhernandez
    - jschueller
