{% set name = "gpflow" %}
{% set version = "2.5.2" %}

package:
  name: gpflow
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gpflow-{{ version }}.tar.gz
  sha256: 87f783916b93e8857f2bf50ca7d3a34e039a6c35583738ce9d11136238f4acc1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - deprecated
    - lark >=1.1.0
    - multipledispatch >=0.6
    - numpy
    - packaging
    - python >=3.7
    - scipy
    - setuptools >=41.0.0
    - tabulate
    - tensorflow >=2.4.0
    - tensorflow-probability >=0.12.0
    - typing-extensions

test:
  imports:
    - gpflow
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/GPflow/GPflow/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Gaussian processes in TensorFlow

extra:
  recipe-maintainers:
    - westinhuang
    - cxhernandez
