{% set version = "2.5.2" %}

package:
  name: gpflow
  version: {{ version }}

source:
  fn: GPflow-{{ version }}.tar.gz
  url: https://github.com/GPflow/GPflow/archive/v{{ version }}.tar.gz
  sha256: ac97fbeb3088a9cb19a04d26ab3affe0eb7f4f19bec761d90c2c25ea51c21b94

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy
    - tensorflow-base >=2,<3
    - tensorflow-probability >=0.12.0,<0.13.0
    - multipledispatch >=0.6
    - tabulate
    - typing_extensions
    - packaging
    - deprecated
    - lark

test:
  imports:
    - gpflow

about:
  home: https://github.com/GPflow/GPflow/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Gaussian processes in TensorFlow

extra:
  recipe-maintainers:
    - cxhernandez
