{% set version = "2.3.1" %}

package:
  name: gpflow
  version: {{ version }}

source:
  fn: GPflow-{{ version }}.tar.gz
  url: https://github.com/GPflow/GPflow/archive/v{{ version }}.tar.gz
  sha256: b1879a699c7cb2fc939427ec4b9eaff67f4129a118717edff649f18c04637220

build:
  number: 0
  skip: true  # [win]
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy
    - tensorflow-base >=2,<3
    - tensorflow-probability >=0.12.0,<0.13.0
    - multipledispatch >=0.6
    - tabulate
    - typing_extensions
    - packaging
    - deprecated

test:
  imports:
    - gpflow

about:
  home: https://github.com/GPflow/GPflow/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Gaussian processes in TensorFlow

extra:
  recipe-maintainers:
    - cxhernandez
    - jschueller
