# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "tSpLbDqtPNKwmKxDzVMw8Hi+alNNAf7gK8YpLlMQgyUqLMvEhSihnC5ML7H2gNSV+1eCFVeQgivHIvFsVfNZDCLKsbDrM+DT955Qw/A9Dnev40O3R/05kLUKbVrom5QLsDO5tD3IojbWNwAlEYz07EOsbUw/dQMUmmXFHUGeQbdFv5VLJy5qp7IfHb9d3ibt0TZtYTc2Ctr8mvAsSG2uc8eMlnG2/psDsqKAbtAFnA1nWK/2GO2I/UJC07Ugek4YjdwGoBipi59gUYVgwJIPMBUfBcB6IUF2ULWBJjq/EIlZs7nYPz+4A/KiXuRt9ovAHDonuIECLwMFTYZJ6RAz4aIYRuQ0CrgfsmBXUC4utikO5iWNA9VbFpOKzcLTXQi1lxDsa6Epc7TAJd5TKfn8iXKnWTy8QYGUqyZax8vl73Yqm9JAJo5TDhEYzIoDRZY9Vb59o+SObO6EEKUSsnNUPK/xrxo2sLKu1FMWob9O0aY2YJ9zIug5WQOYWGq0bbDh4QWUte3uXpJk27RXmH8/vx+VaGQ/m0AU3cli+pfdSUxxEKyz0r0B7I5iLCqgyd6FJQVAGZiYImNTjij+u6irWDoaCLEemkxcG721zQ2U16TU3HlkL6JRT9O+8NH02M/MeynfiKtjbgML/z1YI21y+kgR9htSD7+fUkL/C8XgJ9g="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
