travis:
  secure:
    BINSTAR_TOKEN: JYgSdj8u4nHn+KpdtnnfDtBXwzu7Ie+UnFV6n46xbUyhhLvw2BuhQOuolH/KCT9VQLpjIwG8iWinEL8ll99wp3/jlyC/f0aM3G7pk+CVY9OK2U6a9bY3zoumaQu99d3/BxRWQFZYGzUDXfV/+hUPSFW5YNtQZ4tcDMRxYWqmx8zzGaM4VAmD2BEHiHjx6UJUmvvj+WCP1js2cLA9slhYhiyKHKEsrHYdypIamnqz/DNvc4ha4Zt1YFmCOjm+VzJEjsqo2CUM/YkxKC1rkU0nvyPhBzMqBQfNaW1eEc+hFIHRfNwEaEx2vn9o/2CGmg+g6shS8c+2cCWwiGLvgB8gZAn0HexxzEyGNnUwTAapVYDPMugEEbMr3Ep385FUmBMZABMPQrN4bNM8MXxE2o7TM7Q3bo1HXWgAPH9foIZSU96mDpcsscT7AxAtZEZJOQ0EVIv9p8XPuRsgyRctUB/N7FI5X7iRiczweNAM1kzLcWDyxAoGHN0h26gmeARxyowXsZQNH+bhkkOAusv183ASzRVGnIM5HdEY+UIsdIjcf8tUoyroZ+xJ94Q5pj1U1BBrSpYGl1ZNEk3jfhiDbRrfdrPUjMiGiPjT/Gr72XnuhR+AzDpaoBYbZXdmT09FPB4yBfOdUXO4Nwr4QOGTsZu9/D9evLR3jJ+NJK42qUlMW5Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
