travis:
  secure:
    BINSTAR_TOKEN: tSpLbDqtPNKwmKxDzVMw8Hi+alNNAf7gK8YpLlMQgyUqLMvEhSihnC5ML7H2gNSV+1eCFVeQgivHIvFsVfNZDCLKsbDrM+DT955Qw/A9Dnev40O3R/05kLUKbVrom5QLsDO5tD3IojbWNwAlEYz07EOsbUw/dQMUmmXFHUGeQbdFv5VLJy5qp7IfHb9d3ibt0TZtYTc2Ctr8mvAsSG2uc8eMlnG2/psDsqKAbtAFnA1nWK/2GO2I/UJC07Ugek4YjdwGoBipi59gUYVgwJIPMBUfBcB6IUF2ULWBJjq/EIlZs7nYPz+4A/KiXuRt9ovAHDonuIECLwMFTYZJ6RAz4aIYRuQ0CrgfsmBXUC4utikO5iWNA9VbFpOKzcLTXQi1lxDsa6Epc7TAJd5TKfn8iXKnWTy8QYGUqyZax8vl73Yqm9JAJo5TDhEYzIoDRZY9Vb59o+SObO6EEKUSsnNUPK/xrxo2sLKu1FMWob9O0aY2YJ9zIug5WQOYWGq0bbDh4QWUte3uXpJk27RXmH8/vx+VaGQ/m0AU3cli+pfdSUxxEKyz0r0B7I5iLCqgyd6FJQVAGZiYImNTjij+u6irWDoaCLEemkxcG721zQ2U16TU3HlkL6JRT9O+8NH02M/MeynfiKtjbgML/z1YI21y+kgR9htSD7+fUkL/C8XgJ9g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
